SET SERVEROUTPUT ON;
DECLARE S_ID NUMBER;
        S_NAME VARCHAR(30);
BEGIN
  SELECT FIRST_NAME INTO S_NAME from STUDENT WHERE STUDENT_ID = 400;    
--  SELECT STUDENT_ID INTO S_ID from student WHERE ROWNUM = 1;
--  SELECT FIRST_NAME INTO S_NAME from student WHERE ROWNUM = 1;  
--  DBMS_OUTPUT.PUT_LINE (S_ID);
  DBMS_OUTPUT.PUT_LINE (S_NAME);
  EXCEPTION WHEN NO_DATA_FOUND
  THEN
    DBMS_OUTPUT.PUT_LINE ('NO DATA BASE');
  
END;


--SELECT STUDENT_ID from STUDENT ORDER BY STUDENT_ID DESC;  